### ISSUE TITLE
Non-Premium Users cannot use Playback Controls

### ISSUE THREAD

**Issue by Jyodann** [JordynWinnie/MinifyPlayer#4]
Reproduction Steps:
- Log in with a Non-Premium Account
- Try to use Play, Pause, Next or Previous buttons

Expected Outcome:
- Songs should play or pause.

Actual Outcome: 
- Buttons react, but songs do not play or pause at all

Bug Reported by @Shockch4rge

**Comment by JordynWinnie** [comment]
Sadly, non-Premium users cannot Play, Pause, Move next or move Previous, as seen in this message when testing with a Non-Premium Account:

![image](https://user-images.githubusercontent.com/48559311/206861532-ad993caa-e75b-4f53-9be1-4a1db46d09d6.png)

For now, the newest build has a message at the Login Screen warning of this issue:
![image](https://user-images.githubusercontent.com/48559311/206861608-86a8d160-334c-46bc-a119-4b6ec9c03f47.png)

**Comment by Jyodann** [comment]
Sadly, non-Premium users cannot Play, Pause, Move next or move Previous, as seen in this message when testing with a Non-Premium Account:

![image](https://user-images.githubusercontent.com/48559311/206861532-ad993caa-e75b-4f53-9be1-4a1db46d09d6.png)

For now, the newest build has a message at the Login Screen warning of this issue:
![image](https://user-images.githubusercontent.com/48559311/206861608-86a8d160-334c-46bc-a119-4b6ec9c03f47.png)

In the future, the plan would be to disable playback controls entirely if you are a Non-Premium user, but to check for this, more permissions would be required for the user which seem quite excessive, like [user-read-private](https://developer.spotify.com/documentation/general/guides/authorization-guide/#list-of-scopes)
