### ISSUE TITLE
Initial Setup Issue

### ISSUE THREAD

**Issue by bberg115** [JordynWinnie/MinifyPlayer#7]
I am unable to complete the initial setup. Is this player still working?

Here's my issue... When logging in, I have an error:
` 4. Click Login to Spotify and paste the code in.`

My web browser returns the following:
`INVALID_CLIENT:`` Invalid redirect URI`

for this URL (client ID removed):
https://accounts.spotify.com/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&response_type=code&redirect_uri=https://r59741kpgh.execute-api.ap-southeast-1.amazonaws.com/prod/callback&scope=user-modify-playback-state%20user-read-currently-playing

Any suggestions?

**Comment by Jyodann** [comment]
>  
> 
> I am unable to complete the initial setup. Is this player still working?
> 
> 
> 
> Here's my issue... When logging in, I have an error:
> 
> ` 4. Click Login to Spotify and paste the code in.`
> 
> 
> 
> My web browser returns the following:
> 
> `INVALID_CLIENT:`` Invalid redirect URI`
> 
> 
> 
> for this URL (client ID removed):
> 
> https://accounts.spotify.com/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&response_type=code&redirect_uri=https://r59741kpgh.execute-api.ap-southeast-1.amazonaws.com/prod/callback&scope=user-modify-playback-state%20user-read-currently-playing
> 
> 
> 
> Any suggestions?

Hi Ralph, thanks for using Minify! I have recently created a successor to this application, named Bittify. 

You can find it here: https://github.com/Jyodann/Bittify 

Unfortunately haven't had the time to update Minify's page to reflect that the service is no longer available, but will do so soon! Thanks for your support!

**Comment by Jyodann** [comment]
Hope to see you using Bittify! Thank you for your feedback :D
